[package]
name = "vectis-wallet"
authors = ["bwty <whalelephant@users.noreply.github.com>", "iorveth <aenseidheiorweth@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["ibc3"] }
cosmwasm-schema = { version = "1.1.5" }
sha2 = "0.9"
ripemd160 = "0.9.1"
hex = { version = "0.4", default-features = false }
bech32 = "0.8.1"
primitive-types = {version = "0.10.1", default-features = false, features = ["byteorder"]}
cw2 = "0.13"
thiserror = { version = "1.0.26" }
cw-utils = "0.13"
cw20 = "0.13"
cw20-stake = {git = "https://github.com/nymlab/dao-contracts", features = ["library"], rev = "b82db3243688a5e6ad"}
cw-proposal-single = {git = "https://github.com/nymlab/dao-contracts", features = ["library"], rev = "b82db3243688a5e6ad"}
