[package]
name = "vectis-wallet"
authors = ["bwty <whalelephant@users.noreply.github.com>", "iorveth <aenseidheiorweth@gmail.com>", "j0nl1 <j0nl1@gmail.com>"]
version = "0.2.1"
edition = "2018"
license-file = "LICENSE"
keywords = ["cosmwasm", "account-abstraction", "smart-contract-wallet", "vectis", "cosmos"] 
repository = "https://github.com/nymlab/vectis"
description = "Vectis library for common messages, states and functions"


[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { workspace = true }
cw1 = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw-utils= { workspace = true }
thiserror = { workspace = true }
derivative = "2"
sylvia = {workspace = true}
sylvia-derive = {workspace = true}
sha2 = {workspace = true} 
ripemd160 = {workspace = true}  
hex = { version = "0.4", default-features = false }
bech32 = "0.8.1"
primitive-types = {version = "0.10.1", default-features = false, features = ["byteorder"]}

