[package]
name = "vectis-wallet"
authors = ["bwty <whalelephant@users.noreply.github.com>", "iorveth <aenseidheiorweth@gmail.com>"]
version = "0.1.0"
edition = "2018"


[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cosmwasm-schema = { workspace = true }
cw1 = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw-utils= { workspace = true }
thiserror = { workspace = true }
derivative = "2"

sha2 = "0.9"
ripemd160 = "0.9.1"
hex = { version = "0.4", default-features = false }
bech32 = "0.8.1"
primitive-types = {version = "0.10.1", default-features = false, features = ["byteorder"]}

# daodao contracts
cw20-stake = { workspace = true }
dao-proposal-single = { workspace = true }
dao-pre-propose-approval-single = { workspace = true }
