[workspace]
members = ["packages/*", "contracts/*"]
exclude = ["packages/images"]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release.package.vectis-factory]
codegen-units = 1
incremental = false

[profile.release.package.vectis-proxy]
codegen-units = 1
incremental = false

[profile.release.package.vectis-govec]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false




