[workspace]
members = ["packages/*", "contracts/*"]
exclude = ["packages/images"]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release.package.vectis-factory]
codegen-units = 1
incremental = false

[profile.release.package.vectis-proxy]
codegen-units = 1
incremental = false

[profile.release.package.vectis-govec]
codegen-units = 1
incremental = false

[profile.release.package.vectis-plugin-registry]
codegen-units = 1
incremental = false

[profile.release.package.vectis-dao-tunnel]
codegen-units = 1
incremental = false

[profile.release.package.vectis-remote-tunnel]
codegen-units = 1
incremental = false

[profile.release.package.vectis-remote-factory]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false

[workspace.dependencies]
cosmwasm-std = { version = "1.1", features = ["iterator", "ibc3", "staking"] }
cosmwasm-storage = { version = "1.1" }
cosmwasm-schema = { version = "1.1" }
cw-utils = "0.16"
thiserror = { version = "1.0.30" }
cw-storage-plus = "0.16"
cw1 = "0.16"
cw2 = "0.16"
cw3 = "0.16"
cw4 = "0.16"
cw4-group = "0.16"
cw20 = "0.16"
cw20-base = "0.16"
cw-multi-test = "0.16"
cw-controllers = "0.16"
anyhow = { version = "1.0.51"}
rand = "0.8"
serde = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["derive"] }

# daodao contracts
dao-core = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190", features = ["library"]}
dao-proposal-single = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190", features = ["library"]}
dao-pre-propose-approval-single = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190", features = ["library"]}
dao-pre-propose-base = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190"}
dao-voting-cw20-staked = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190", features = ["library"]}
cw20-stake = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190", features = ["library"]}
dao-voting = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190"}
dao-interface = {git = "https://github.com/nymlab/dao-contracts",  rev = "f17b3e74e8190"}
