[workspace]
members = ["packages/*", "contracts/core/*", "contracts/plugins/*"]
exclude = ["packages/images"]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release.package.vectis-factory]
codegen-units = 1
incremental = false

[profile.release.package.vectis-proxy]
codegen-units = 1
incremental = false

[profile.release.package.vectis-plugin-registry]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false

[workspace.dependencies]
cosmwasm-std = { version = "1.2", features = ["iterator", "ibc3", "staking", "cosmwasm_1_2"] }
cosmwasm-storage = "1.2" 
cosmwasm-schema = "1.2" 
sylvia = "0.7.0"
sylvia-derive = "0.7.0"
cw-utils = "1.0.1"
thiserror = { version = "1.0.30" }
cw-storage-plus = "1.1"
cw1 = "1.1"
cw2 = "1.1"
cw3 = "1.1"
cw4 = "1.1"
cw4-group = "1.1"
cw20 = "1.1"
cw20-base = "1.1"
cw-multi-test = "0.16"
anyhow = { version = "1.0.51"}
rand = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["derive"] }

