/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Uint128, InstantiateMsg, Coin, ExecuteMsg, ExecMsg, QueryMsg, QueryMsg1 } from "./PluginRegistry.types";
export interface PluginRegistryReadOnlyInterface {
    contractAddress: string;
}
export class PluginRegistryQueryClient implements PluginRegistryReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;

    constructor(client: CosmWasmClient, contractAddress: string) {
        this.client = client;
        this.contractAddress = contractAddress;
    }
}
