[package]
name = "vectis-plugin-registry"
version = "0.1.0"
authors = ["bwty <whalelephant@users.noreply.github.com>", "j0nl1 <j0nl1@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-std = { version = "1.1.6", features = ["staking"] }
cosmwasm-schema = { version = "1.1.6" }
serde = { version = "1", default-features = false, features = ["derive"] }
cw-storage-plus = "1.0"
sylvia = "0.2.1"
sylvia-derive = "0.2.1"
cw2 = "1.0"
cw-utils = "1.0"
thiserror = { version = "1.0.37" }

[dev-dependencies]
