[package]
name = "sc-wallet"
authors = ["bwty <whalelephant@users.noreply.github.com>", "iorveth <aenseidheiorweth@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.0.0-beta7" }
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
sha2 = "0.9"
ripemd160 = "0.9.1"
hex = { version = "0.4", default-features = false }
bech32 = "0.8.1"
primitive-types = {version = "0.10.1", default-features = false, features = ["byteorder"]}
cw2 = "0.13.0"
thiserror = { version = "1.0.26" }
cw-utils = "0.11"
cw20 = "0.13.0"
govec = { path = "../../contracts/govec", features = ["library"] }
