/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { InstantiateMsg, ExecuteMsg, AuthenticatorTraitExecMsg, ExecMsg, QueryMsg, AuthenticatorTraitQueryMsg, QueryMsg1, Boolean, ContractVersion } from "../types/webauthn.type";
import { CamelCasedProperties } from "type-fest";
export abstract class WebauthnQueryMsgBuilder {
  static authenticate = ({
    controllerData,
    metadata,
    signature,
    signedData
  }: CamelCasedProperties<Extract<QueryMsg, {
    authenticate: unknown;
  }>["authenticate"]>): QueryMsg => {
    return {
      authenticate: ({
        controller_data: controllerData,
        metadata,
        signature,
        signed_data: signedData
      } as const)
    };
  };
  static contractVersion = (): QueryMsg => {
    return {
      contract_version: ({} as const)
    };
  };
}