/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Uint128 = string;
export type LogoInfo =
    | {
          url: string;
      }
    | "embedded";
export type Addr = string;
export interface InstantiateMsg {
    initial_balances: Cw20Coin[];
    marketing?: MarketingInfoResponse | null;
    mint_amount: Uint128;
    mint_cap?: Uint128 | null;
    name: string;
    symbol: string;
}
export interface Cw20Coin {
    address: string;
    amount: Uint128;
}
export interface MarketingInfoResponse {
    description?: string | null;
    logo?: LogoInfo | null;
    marketing?: Addr | null;
    project?: string | null;
    [k: string]: unknown;
}
export type ExecuteMsg =
    | {
          transfer: {
              amount: Uint128;
              recipient: string;
              relayed_from?: string | null;
          };
      }
    | {
          transfer_from: {
              amount: Uint128;
              owner: string;
              recipient: string;
          };
      }
    | {
          burn: {
              amount: Uint128;
          };
      }
    | {
          exit: {
              relayed_from?: string | null;
          };
      }
    | {
          send: {
              amount: Uint128;
              contract: string;
              msg: Binary;
              relayed_from?: string | null;
          };
      }
    | {
          mint: {
              new_wallet: string;
          };
      }
    | {
          update_mint_cap: {
              new_mint_cap?: Uint128 | null;
          };
      }
    | {
          update_mint_amount: {
              new_amount: Uint128;
          };
      }
    | {
          update_dao_addr: {
              new_addr: string;
          };
      }
    | {
          update_marketing: {
              description?: string | null;
              marketing?: string | null;
              project?: string | null;
          };
      }
    | {
          upload_logo: Logo;
      };
export type Binary = string;
export type Logo =
    | {
          url: string;
      }
    | {
          embedded: EmbeddedLogo;
      };
export type EmbeddedLogo =
    | {
          svg: Binary;
      }
    | {
          png: Binary;
      };
export type QueryMsg =
    | {
          balance: {
              address: string;
          };
      }
    | {
          joined: {
              address: string;
          };
      }
    | {
          token_info: {};
      }
    | {
          mint_amount: {};
      }
    | {
          minters: {};
      }
    | {
          dao: {};
      }
    | {
          all_accounts: {
              limit?: number | null;
              start_after?: string | null;
          };
      }
    | {
          marketing_info: {};
      }
    | {
          download_logo: {};
      }
    | {
          token_contract: {};
      };
export interface AllAccountsResponse {
    accounts: string[];
    [k: string]: unknown;
}
export interface BalanceResponse {
    balance: Uint128;
}
export interface DownloadLogoResponse {
    data: Binary;
    mime_type: string;
}
export type NullableBalanceResponse = BalanceResponse | null;
export interface MintResponse {
    cap?: Uint128 | null;
    minters?: string[] | null;
}
export type String = string;
export interface TokenInfoResponse {
    decimals: number;
    name: string;
    symbol: string;
    total_supply: Uint128;
}
