src: juno-1
dest: juno-2
mnemonic: useful guitar throw awesome later damage film tonight escape burger powder manage exact start title december impulse random similar eager smart absurd unaware enlist