version: 1

chains:
  juno-1:
    chain_id: juno-1
    prefix: juno
    gas_price: 0.1ujunox
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    estimated_block_time: 7000
    estimated_indexer_time: 250
    rpc:
      - http://localhost:26647
  juno-2:
    chain_id: juno-2
    prefix: juno
    gas_price: 0.1ujunox
    hd_path: m/44'/118'/0'/0/0
    ics20_port: 'transfer'
    estimated_block_time: 7000
    estimated_indexer_time: 250
    rpc:
      - http://localhost:26657
