name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    env: 
      RUSTDOCFLAGS=: "--enable-index-page -Zunstable-options"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            override: true
            components: rust-docs

      - name: Building Documentation
        run: cargo +nightly doc --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc