name: Test Tube Tests

on:
  pull_request:
  push:
    branches:
      - test-tube

jobs:
  test-tube-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      GAS_OUT_DIR: gas_reports
      GAS_LIMIT: 100000000
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-02-02
          target: wasm32-unknown-unknown
          override: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1

      - name: Clone libwasmv (needed for test-tube)
        uses: actions/checkout@v2
        with:
          repository: CosmWasm/wasmvm
          path: ./wasmvm
          ref: v1.4.1
          token: ${{ secrets.GH_TOKEN }}

      - name: Install libwasmv
        run: cd ./wasmvm && make build-rust && cd ../

      - name: Rust Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            artifacts/
          key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('**/Cargo.lock') }}

      - name: Run build-contracts
        run: make build-contracts

      - name: Run Test Tube Integration Tests
        run: UNAME=$(uname -p) cargo test -- test-tube
