name: Test Tube Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-tube-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.1

      - name: Clone libwasmv (needed for test-tube)
        uses: actions/checkout@v2
        with:
          repository: CosmWasm/wasmvm
          path: ./wasmvm
          ref: v1.4.1
          token: ${{ secrets.GH_TOKEN }}

      - name: Install libwasmv
        run: cd ./wasmvm && make build-rust && cd ../

      - name: Download passkey-cli repo
        uses: actions/checkout@v4
        with:
          repository: nymlab/passkey-cli
          path: ./passkey-cli
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Install passkey-cli
        run: |
          cd ./passkey-cli
          cargo build --release
          cp target/release/passkey-cli ../packages/vectis-tests
          cd ../

      - name: Run build-contracts
        run: make build-contracts

      - name: Run All Integration Tests
        run: |
          rm -rf target
          cargo test -- test_tube
        env:
          RUST_BACKTRACE: 1
