name: Test, Lint and Build Checker

on: 
  push:
    branches: 
      - main
  pull_request:

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    env: 
      RUSTFLAGS: "-Cinstrument-coverage"
      LLVM_PROFILE_FILE: "vectis-%p-%m.profraw"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.61.0
          target: wasm32-unknown-unknown
          override: true

      - name: Install Coverage Dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview
      
      - name: Run contract tests for remote chain
        run: cargo test
        env:
          RUST_BACKTRACE: 1

      - name: Generate LCOV Report
        run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./lcov.info

      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
  
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Compile WASM contract factory dao chain
        run: cargo wasm-factory-dao-chain --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Compile WASM contract factory remote chain
        run: cargo wasm-factory-remote-chain --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Compile WASM contract proxy
        run: cargo wasm-proxy --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Compile WASM contract govec 
        run: cargo wasm-govec --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Compile WASM contract dao tunnel 
        run: cargo wasm-dao-tunnel --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Compile WASM contract remote tunnel 
        run: cargo wasm-remote-tunnel --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Compile WASM contract remote factory 
        run: cargo wasm-remote-factory --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.64.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
