name: Publish Types to NPM Registry
on:
  workflow_dispatch:
    inputs:
      version_bump:
        required: true
        type: choice
        description: "Define your bump version change"
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run types:generate
      - run: npm run types:version ${{ github.event.inputs.version_bump }}
      - run: npm run types:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit Version
        env:
          TYPES_VERSION: node -pe "require('./types/package.json').version"
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: "bumping types package version"
          add: "."

